{% set version = '2.1-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-uroot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/uroot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/uroot/uroot_{{ version }}.tar.gz
  sha256: 3c02a9dadd22aa67a59e99007ab6f576dc428859fa746d3a8f3ffa2bb43d18c2

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('uroot')"           # [not win]
    - "\"%R%\" -e \"library('uroot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=uroot
  license: GPL-2
  summary: Seasonal unit roots and seasonal stability tests. P-values based on response surface
    regressions are available for both tests. P-values based on bootstrap are available
    for seasonal unit root tests.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - philip-khor
    - conda-forge/r

# Package: uroot
# Version: 2.1-0
# Date: 2019-08-19
# Title: Unit Root Tests for Seasonal Time Series
# Authors@R: c( person(given = "Javier", family = "Lopez-de-Lacalle", role = c("aut"), email = "javlacalle@yahoo.es"), person(given = c("Georgi", "N."), family = "Boshnakov", role = c("cre"), email = "georgi.boshnakov@manchester.ac.uk") )
# Depends: R (>= 3.0.0), stats
# Encoding: UTF-8
# Description: Seasonal unit roots and seasonal stability tests. P-values based on response surface regressions are available for both tests. P-values based on bootstrap are available for seasonal unit root tests.
# LazyData: yes
# LazyDataCompression: xz
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2019-08-19 14:23:27 UTC; georgi
# Author: Javier Lopez-de-Lacalle [aut], Georgi N. Boshnakov [cre]
# Maintainer: Georgi N. Boshnakov <georgi.boshnakov@manchester.ac.uk>
# Repository: CRAN
# Date/Publication: 2019-08-19 18:10:03 UTC
