{% set version = '2.0-10' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-uroot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/uroot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/uroot/uroot_{{ version }}.tar.gz
  sha256: 723649f95d3b2543486ec6d5d82cca5448a7e3b6df467287d1a5ee9d7f2e8e00

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('uroot')"           # [not win]
    - "\"%R%\" -e \"library('uroot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=uroot
  license: GPL-2
  summary: Seasonal unit roots and seasonal stability tests. P-values based on response surface
    regressions are available for both tests. P-values based on bootstrap are available
    for seasonal unit root tests. A parallel implementation of the bootstrap method
    requires a CUDA capable GPU  with compute capability >= 3.0, otherwise a debugging
    version fully coded in R is used.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - philip-khor
    - conda-forge/r

# Package: uroot
# Version: 2.0-10
# Date: 2019-06-18
# Title: Unit Root Tests for Seasonal Time Series
# Authors@R: c( person(given = "Javier", family = "Lopez-de-Lacalle", role = c("aut"),  email = "javlacalle@yahoo.es"), person(given = c("Georgi", "N."), family = "Boshnakov",  role = c("cre"),  email = "georgi.boshnakov@manchester.ac.uk") )
# Depends: R (>= 3.0.0), stats
# SystemRequirements: nvcc (release >= 7.1) (NVIDIA Cuda Compiler driver)
# Encoding: UTF-8
# Description: Seasonal unit roots and seasonal stability tests. P-values based on response surface regressions are available for both tests. P-values based on bootstrap are available for seasonal unit root tests. A parallel implementation of the bootstrap method requires a CUDA capable GPU  with compute capability >= 3.0, otherwise a debugging version fully coded in R is used.
# NeedsCompilation: yes
# LazyData: yes
# LazyDataCompression: xz
# License: GPL-2
# Packaged: 2019-06-18 07:00:59 UTC; georgi
# Author: Javier Lopez-de-Lacalle [aut], Georgi N. Boshnakov [cre]
# Maintainer: Georgi N. Boshnakov <georgi.boshnakov@manchester.ac.uk>
# Repository: CRAN
# Date/Publication: 2019-06-24 18:20:03 UTC
